version: "3.3"

networks:
  laravel:
    external: true

services:
  redis:
    image: redis:alpine
    networks:
      - laravel
    ports:
      - "6379:6379"

  websocket:
    build: .
    ports:
      - "3001:3001"
    environment:
      REDIS_HOST: redis-server             # nombre del servicio redis
      REDIS_PORT: 6379
      LARAVEL_API_URL: http://ccerpback  # nombre del servicio laravel
      CORS_ORIGIN: http://127.0.0.1:5500
      PORT: 3001
    depends_on:
      - redis
    networks:
      - laravel
