version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  websocket:
    build: .
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LARAVEL_API_URL=http://host.docker.internal
    depends_on:
      - redis
