version: "3.3"

networks:
  laravel:
    external: true

services:
  websocket:
    build: .
    ports:
      - "3001:3001"
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      LARAVEL_API_URL: http://ccerpback
      CORS_ORIGIN: http://127.0.0.1:5500
      PORT: 3001
    networks:
      - laravel
